#!/bin/bash
# bootstrap hello-world
# assume-role to the correct account
set -e

go build . # Build step for your operating system

# Build step (called lambda) for linux lambda
GOOS=linux go build -o lambda
zip lambda.zip lambda

step bootstrap                        \
  -lambda "coinbase-step-hello-world" \
  -step "coinbase-step-hello-world"   \
  -states "$(./step-hello-world json)"
