#!/bin/bash
# bootstrap hello-world
# assume-role to the correct account
set -e

ARN="arn:aws:states:${AWS_REGION}:${AWS_ACCOUNT_ID}:stateMachine:coinbase-step-hello-world"

EXECUTION_ARN=$(aws stepfunctions start-execution \
                     --state-machine-arn $ARN \
                     --input '{}' | jq -r ".executionArn" )

echo "Started $EXECUTION_ARN"

sleep 1

aws stepfunctions describe-execution --execution-arn $EXECUTION_ARN

aws stepfunctions get-execution-history --execution-arn $EXECUTION_ARN
